---
- name: Add python3 repository
  apt_repository:
    repo: "ppa:jonathonf/python-3.6"
    state: present

- name: Update server
  apt: update_cache=yes cache_valid_time=3600
  sudo: true

- name: Install common packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
      - "rsync"
      - "python3.6"
      - "python-mysqldb"
      - "python-pymysql"
      - "git"

- name: Upgrade server
  apt: upgrade=full
