---
- name: Install NGINX
  apt:
    name: "nginx"
    state: present
    update_cache: yes

- name: write nginx.conf
  action: template src='templates/nginx.conf.j2' dest='/etc/nginx/nginx.conf' backup=yes

- name: write site-enabled "{{ website_name }}"
  template:
    src: "{{ nginx_template }}/website.j2"
    dest: "{{ website_origin }}"
    backup: yes

- name: Create symlink "{{ website_name }}"
  file:
    src: "{{ website_origin }}"
    dest: "{{ website_link }}"
    state: link

- name: start nginx
  action: service name=nginx state=started

- name: restart nginx
  raw: service nginx reload
  sudo: true
