---
- hosts: server
  become: True

  vars:
    website_link: "/etc/nginx/sites-enabled/{{ website_name }}"
    #Locations
    nginx_template: nginx/templates
    website_origin: "/etc/nginx/sites-available/{{ website_name }}"
    website_name: {{ website }}

    #Versions
    php_version: "7.2"
    mysql_version: "5.7"

    #loggins
    db_user: "user"
    db_pass: "pass"
    db_name: "dbname"
    db_host: "localhost"


    #Lists
    repo: ['ppa:jonathonf/python-3.6', 'ppa:ondrej/php']
    packages:
      - "rsync"
      - "python3.6"
      - "python-mysqldb"
      - "python-pymysql"
      - "git"
      - "nginx"
      - "mysql-server-{{ mysql_version }}"
      - "php{{ php_version }}-fpm"
      - "php{{ php_version }}-mysql"
      - "php{{ php_version }}-curl"
      - "php{{ php_version }}-gd"
      - "php{{ php_version }}-mbstring"
      - "php-mcrypt"
      - "php{{ php_version }}-xml"
      - "php{{ php_version }}-xmlrpc"


  tasks:
    ##
    # installing packages
    ##
    - apt_repository:
        repo: "{{ item }}"
        state: present
      loop: "{{ repo }}"

    - name: Upgrade all packages to the latest version
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install LEMP enviroment
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop: "{{ packages }}"

    - name: write nginx.conf
      action: template src='nginx/templates/nginx.conf.j2' dest='/etc/nginx/nginx.conf' backup=yes

    - name: write site-enabled "{{ website_name }}"
      template:
        src: "{{ nginx_template }}/website.j2"
        dest: "{{ website_origin }}"
        backup: yes

      notify:
        - Reload Nginx
        - Restart php

    - name: Create symlink "{{ website_name }}"
      file:
        src: "{{ website_origin }}"
        dest: "{{ website_link }}"
        state: link
      notify: Reload Nginx

    # Configure DB
    - name: write my.cnf
      template:
        src: "mysql/templates/my.cnf.j2"
        dest: /root/.my.cnf
        owner: "{{ db_user }}"
        mode: 0600
      notify:
        - restart mysql

    - name: Create db user
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_pass }}"
        priv: '*.*:ALL,GRANT'
        state: present

    - name: Create database
      mysql_db:
        name: "{{ db_name }}"
        state: present
        login_user: "{{ db_user }}"
        login_password: "{{ db_pass }}"


  handlers:
    ##
    # restart services
    ##
    - name: Restart php
      action: service name=php{{ php_version }}-fpm state=restarted

    - name: Reload Nginx
      action: service name=nginx state=reloaded

    - name: restart mysql
      action: service name=mysql state=restarted
